default_title: Austin Bagley
meta_description: A how-to blog for the modern marketer by Austin Bagley, startup marketer, developer, brand manager, and BYU MBA.
meta_keywords: Austin Bagley, BYU, MBA, Marriott School, Marketing, Martech, Adtech, Marketing Stack, Startup Marketing, Brand Management
test: test
